version: "3.8"

services:
  weaviate:
    image: semitechnologies/weaviate:1.27.4 # ou :latest
    restart: always
    ports:
      - "8080:8080"    # API REST
      - "50051:50051"  # API gRPC (n√©cessaire pour le client v4)
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "vitiscan-weaviate"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
