name: vitiscan-rag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi[standard]==0.115.0
      - uvicorn==0.41.0
      - python-dotenv==1.0.1
      - weaviate-client==4.19.4
      - sentence-transformers==5.2.3
      - transformers==5.2.0
      - pydantic>=2.12.0,<3
      - python-frontmatter==1.1.0
      - requests>=2.31.0,<3
      - huggingface_hub==1.4.1
      - pytest>=8.0.0
      - httpx>=0.27.0
