name: vitiscan-rag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - python-dotenv
      - weaviate-client
      - sentence-transformers
      - transformers
      - pydantic
      - unidecode
      - python-frontmatter
      - markdown
      - requests
